/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118460-g78ff3782af-20250211"
#endif /* AVUTIL_FFVERSION_H */
